name: Daily Commit

on:
  schedule:
    - cron: '10 17 * * *'  # 00:10 WIB
  workflow_dispatch:       # Bisa manual juga

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Git Identity
        run: |
          git config user.name "Aphexya Bot"
          git config user.email "aphexya@users.noreply.github.com"

      - name: Make Daily Update
        run: |
          echo "🗓️ Commit at $(TZ='Asia/Jakarta' date)" >> daily.md

      - name: Commit and Push
        run: |
          git add daily.md
          git commit -m "🕒 Daily commit at $(date '+%Y-%m-%d %H:%M:%S')"
          git push
